apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - image: galoomba12/udagram-feeds-service
        name: backend-feed
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        env:
        - name: URL
          value: "http://localhost:8100"
        - name: AWS_BUCKET
          value: "udagram-cbucket"
        - name: JWT_SECRET
          value: "hello"
        - name: POSTGRESS_DB
          value: "postgre"
        - name: POSTGRESS_HOST
          value: "udagram-database.cf4hqgnainiv.us-east-2.rds.amazonaws.com"
        - name: POSTGRESS_PASSWORD
          value: "toortoor"
        - name: POSTGRESS_USERNAME
          value: "root"
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret       