apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: galoomba12/udagram-user-service
        name: backend-user 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"      
        env:
        - name: URL
          value: "$URL"
        - name: AWS_BUCKET
          value: "$AWS_BUCKET"
        - name: JWT_SECRET
          value: "$JWT_SECRET"
        - name: POSTGRESS_DB
          value: "$POSTGRESS_DB"
        - name: POSTGRESS_HOST
          value: "$POSTGRESS_HOST"
        - name: POSTGRESS_PASSWORD
          value: "$POSTGRESS_PASSWORD"
        - name: POSTGRESS_USERNAME
          value: "$POSTGRESS_USERNAME"
      restartPolicy: Always


