apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: backend-user
    spec:
      containers:
      - image: galoomba12/udagram-user-service
        name: backend-user 
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"      
        env:
        - name: URL
          value: "http://localhost:8100"
        - name: AWS_BUCKET
          value: "udagram-cbucket"
        - name: JWT_SECRET
          value: "hello"
        - name: POSTGRESS_DB
          value: "postgre"
        - name: POSTGRESS_HOST
          value: "udagram-database.cf4hqgnainiv.us-east-2.rds.amazonaws.com"
        - name: POSTGRESS_PASSWORD
          value: "toortoor"
        - name: POSTGRESS_USERNAME
          value: "root"
      restartPolicy: Always


